name: CI

on: [push]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends cmake pkg-config make gcc curl clang clang-tidy clang-format git valgrind util-linux libsfml-dev
        cmake .
        make

