name: CI

on: [push]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make libsfml-dev build-essentials
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cmake .
        make

